// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.xiang.proto.reader.nano;

@SuppressWarnings("hiding")
public interface Reader {

  public static final class Request10001 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .com.xiang.proto.Category category = 1;
      public int category;

      // optional int32 index = 2;
      public int index;

      public Params() {
        clear();
      }

      public Params clear() {
        category = com.xiang.proto.nano.Common.MAIN;
        index = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.category != com.xiang.proto.nano.Common.MAIN) {
          output.writeInt32(1, this.category);
        }
        if (this.index != 0) {
          output.writeInt32(2, this.index);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.category != com.xiang.proto.nano.Common.MAIN) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.category);
        }
        if (this.index != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(2, this.index);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              int value = input.readInt32();
              switch (value) {
                case com.xiang.proto.nano.Common.MAIN:
                case com.xiang.proto.nano.Common.DEEP:
                case com.xiang.proto.nano.Common.IMAGES:
                case com.xiang.proto.nano.Common.PEOPLE:
                case com.xiang.proto.nano.Common.FORFUN:
                case com.xiang.proto.nano.Common.FOREIGN:
                  this.category = value;
                  break;
              }
              break;
            }
            case 16: {
              this.index = input.readInt32();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request10001[] _emptyArray;
    public static Request10001[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request10001[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.reader.Request10001.Params params = 2;
    public com.xiang.proto.reader.nano.Reader.Request10001.Params params;

    public Request10001() {
      clear();
    }

    public Request10001 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request10001 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.reader.nano.Reader.Request10001.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request10001 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request10001(), data);
    }

    public static Request10001 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request10001().mergeFrom(input);
    }
  }

  public static final class Response10001 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // repeated .com.xiang.proto.Article articles = 1;
      public com.xiang.proto.nano.Common.Article[] articles;

      // optional int32 maxCount = 2;
      public int maxCount;

      public Data() {
        clear();
      }

      public Data clear() {
        articles = com.xiang.proto.nano.Common.Article.emptyArray();
        maxCount = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.articles != null && this.articles.length > 0) {
          for (int i = 0; i < this.articles.length; i++) {
            com.xiang.proto.nano.Common.Article element = this.articles[i];
            if (element != null) {
              output.writeMessage(1, element);
            }
          }
        }
        if (this.maxCount != 0) {
          output.writeInt32(2, this.maxCount);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.articles != null && this.articles.length > 0) {
          for (int i = 0; i < this.articles.length; i++) {
            com.xiang.proto.nano.Common.Article element = this.articles[i];
            if (element != null) {
              size += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(1, element);
            }
          }
        }
        if (this.maxCount != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(2, this.maxCount);
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              int arrayLength = com.google.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 10);
              int i = this.articles == null ? 0 : this.articles.length;
              com.xiang.proto.nano.Common.Article[] newArray =
                  new com.xiang.proto.nano.Common.Article[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.articles, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new com.xiang.proto.nano.Common.Article();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new com.xiang.proto.nano.Common.Article();
              input.readMessage(newArray[i]);
              this.articles = newArray;
              break;
            }
            case 16: {
              this.maxCount = input.readInt32();
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response10001[] _emptyArray;
    public static Response10001[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response10001[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.reader.Response10001.Data data = 2;
    public com.xiang.proto.reader.nano.Reader.Response10001.Data data;

    public Response10001() {
      clear();
    }

    public Response10001 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response10001 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.reader.nano.Reader.Response10001.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response10001 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response10001(), data);
    }

    public static Response10001 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response10001().mergeFrom(input);
    }
  }

  public static final class Request10002 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string keyword = 1;
      public java.lang.String keyword;

      // optional int32 index = 2;
      public int index;

      public Params() {
        clear();
      }

      public Params clear() {
        keyword = "";
        index = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.keyword.equals("")) {
          output.writeString(1, this.keyword);
        }
        if (this.index != 0) {
          output.writeInt32(2, this.index);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.keyword.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.keyword);
        }
        if (this.index != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(2, this.index);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.keyword = input.readString();
              break;
            }
            case 16: {
              this.index = input.readInt32();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request10002[] _emptyArray;
    public static Request10002[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request10002[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.reader.Request10002.Params params = 2;
    public com.xiang.proto.reader.nano.Reader.Request10002.Params params;

    public Request10002() {
      clear();
    }

    public Request10002 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request10002 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.reader.nano.Reader.Request10002.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request10002 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request10002(), data);
    }

    public static Request10002 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request10002().mergeFrom(input);
    }
  }

  public static final class Response10002 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // repeated .com.xiang.proto.Article articles = 1;
      public com.xiang.proto.nano.Common.Article[] articles;

      // optional int32 maxCount = 2;
      public int maxCount;

      public Data() {
        clear();
      }

      public Data clear() {
        articles = com.xiang.proto.nano.Common.Article.emptyArray();
        maxCount = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.articles != null && this.articles.length > 0) {
          for (int i = 0; i < this.articles.length; i++) {
            com.xiang.proto.nano.Common.Article element = this.articles[i];
            if (element != null) {
              output.writeMessage(1, element);
            }
          }
        }
        if (this.maxCount != 0) {
          output.writeInt32(2, this.maxCount);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.articles != null && this.articles.length > 0) {
          for (int i = 0; i < this.articles.length; i++) {
            com.xiang.proto.nano.Common.Article element = this.articles[i];
            if (element != null) {
              size += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(1, element);
            }
          }
        }
        if (this.maxCount != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(2, this.maxCount);
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              int arrayLength = com.google.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 10);
              int i = this.articles == null ? 0 : this.articles.length;
              com.xiang.proto.nano.Common.Article[] newArray =
                  new com.xiang.proto.nano.Common.Article[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.articles, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new com.xiang.proto.nano.Common.Article();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new com.xiang.proto.nano.Common.Article();
              input.readMessage(newArray[i]);
              this.articles = newArray;
              break;
            }
            case 16: {
              this.maxCount = input.readInt32();
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response10002[] _emptyArray;
    public static Response10002[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response10002[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.reader.Response10002.Data data = 2;
    public com.xiang.proto.reader.nano.Reader.Response10002.Data data;

    public Response10002() {
      clear();
    }

    public Response10002 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response10002 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.reader.nano.Reader.Response10002.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response10002 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response10002(), data);
    }

    public static Response10002 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response10002().mergeFrom(input);
    }
  }

  public static final class Request10003 extends
      com.google.protobuf.nano.MessageNano {

    // enum OptionType
    public static final int COLLECT = 0;
    public static final int UNCOLLECT = 1;

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional int32 articleId = 1;
      public int articleId;

      // optional .com.xiang.proto.Category category = 2;
      public int category;

      // optional .com.xiang.proto.reader.Request10003.OptionType optionType = 3;
      public int optionType;

      public Params() {
        clear();
      }

      public Params clear() {
        articleId = 0;
        category = com.xiang.proto.nano.Common.MAIN;
        optionType = com.xiang.proto.reader.nano.Reader.Request10003.COLLECT;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.articleId != 0) {
          output.writeInt32(1, this.articleId);
        }
        if (this.category != com.xiang.proto.nano.Common.MAIN) {
          output.writeInt32(2, this.category);
        }
        if (this.optionType != com.xiang.proto.reader.nano.Reader.Request10003.COLLECT) {
          output.writeInt32(3, this.optionType);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.articleId != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(1, this.articleId);
        }
        if (this.category != com.xiang.proto.nano.Common.MAIN) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.category);
        }
        if (this.optionType != com.xiang.proto.reader.nano.Reader.Request10003.COLLECT) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.optionType);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              this.articleId = input.readInt32();
              break;
            }
            case 16: {
              int value = input.readInt32();
              switch (value) {
                case com.xiang.proto.nano.Common.MAIN:
                case com.xiang.proto.nano.Common.DEEP:
                case com.xiang.proto.nano.Common.IMAGES:
                case com.xiang.proto.nano.Common.PEOPLE:
                case com.xiang.proto.nano.Common.FORFUN:
                case com.xiang.proto.nano.Common.FOREIGN:
                  this.category = value;
                  break;
              }
              break;
            }
            case 24: {
              int value = input.readInt32();
              switch (value) {
                case com.xiang.proto.reader.nano.Reader.Request10003.COLLECT:
                case com.xiang.proto.reader.nano.Reader.Request10003.UNCOLLECT:
                  this.optionType = value;
                  break;
              }
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request10003[] _emptyArray;
    public static Request10003[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request10003[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.reader.Request10003.Params params = 2;
    public com.xiang.proto.reader.nano.Reader.Request10003.Params params;

    public Request10003() {
      clear();
    }

    public Request10003 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request10003 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.reader.nano.Reader.Request10003.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request10003 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request10003(), data);
    }

    public static Request10003 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request10003().mergeFrom(input);
    }
  }

  public static final class Response10003 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      public Data() {
        clear();
      }

      public Data clear() {
        cachedSize = -1;
        return this;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response10003[] _emptyArray;
    public static Response10003[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response10003[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.reader.Response10003.Data data = 2;
    public com.xiang.proto.reader.nano.Reader.Response10003.Data data;

    public Response10003() {
      clear();
    }

    public Response10003 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response10003 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.reader.nano.Reader.Response10003.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response10003 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response10003(), data);
    }

    public static Response10003 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response10003().mergeFrom(input);
    }
  }

  public static final class Request10004 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional int32 articleId = 1;
      public int articleId;

      // optional .com.xiang.proto.Category category = 2;
      public int category;

      public Params() {
        clear();
      }

      public Params clear() {
        articleId = 0;
        category = com.xiang.proto.nano.Common.MAIN;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.articleId != 0) {
          output.writeInt32(1, this.articleId);
        }
        if (this.category != com.xiang.proto.nano.Common.MAIN) {
          output.writeInt32(2, this.category);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.articleId != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(1, this.articleId);
        }
        if (this.category != com.xiang.proto.nano.Common.MAIN) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.category);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              this.articleId = input.readInt32();
              break;
            }
            case 16: {
              int value = input.readInt32();
              switch (value) {
                case com.xiang.proto.nano.Common.MAIN:
                case com.xiang.proto.nano.Common.DEEP:
                case com.xiang.proto.nano.Common.IMAGES:
                case com.xiang.proto.nano.Common.PEOPLE:
                case com.xiang.proto.nano.Common.FORFUN:
                case com.xiang.proto.nano.Common.FOREIGN:
                  this.category = value;
                  break;
              }
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request10004[] _emptyArray;
    public static Request10004[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request10004[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.reader.Request10004.Params params = 2;
    public com.xiang.proto.reader.nano.Reader.Request10004.Params params;

    public Request10004() {
      clear();
    }

    public Request10004 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request10004 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.reader.nano.Reader.Request10004.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request10004 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request10004(), data);
    }

    public static Request10004 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request10004().mergeFrom(input);
    }
  }

  public static final class Response10004 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .com.xiang.proto.Article article = 1;
      public com.xiang.proto.nano.Common.Article article;

      public Data() {
        clear();
      }

      public Data clear() {
        article = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.article != null) {
          output.writeMessage(1, this.article);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.article != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.article);
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.article == null) {
                this.article = new com.xiang.proto.nano.Common.Article();
              }
              input.readMessage(this.article);
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response10004[] _emptyArray;
    public static Response10004[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response10004[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.reader.Response10004.Data data = 2;
    public com.xiang.proto.reader.nano.Reader.Response10004.Data data;

    public Response10004() {
      clear();
    }

    public Response10004 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response10004 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.reader.nano.Reader.Response10004.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response10004 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response10004(), data);
    }

    public static Response10004 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response10004().mergeFrom(input);
    }
  }
}
