// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pilot.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class DetailUser;
@class Request11001_Params;
@class Request11002_Params;
@class Request11003_Params;
@class Request11004_Params;
@class Request11005_Params;
@class Request11006_Params;
@class Request11007_Params;
@class RequestCommon;
@class Response11001_Data;
@class Response11002_Data;
@class Response11003_Data;
@class Response11004_Data;
@class Response11005_Data;
@class Response11006_Data;
@class Response11007_Data;
@class ResponseCommon;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PilotRoot

@interface PilotRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Request11001

typedef GPB_ENUM(Request11001_FieldNumber) {
  Request11001_FieldNumber_Common = 1,
  Request11001_FieldNumber_Params = 2,
};

// 验证用户名
// url: /pilot/verifyUsername
@interface Request11001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11001_Params *params;

@end

#pragma mark - Request11001_Params

typedef GPB_ENUM(Request11001_Params_FieldNumber) {
  Request11001_Params_FieldNumber_UserName = 1,
};

@interface Request11001_Params : GPBMessage

// 需要验证的用户名
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@end

#pragma mark - Response11001

typedef GPB_ENUM(Response11001_FieldNumber) {
  Response11001_FieldNumber_Common = 1,
  Response11001_FieldNumber_Data_p = 2,
};

@interface Response11001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11001_Data *data_p;

@end

#pragma mark - Response11001_Data

@interface Response11001_Data : GPBMessage

@end

#pragma mark - Request11002

typedef GPB_ENUM(Request11002_FieldNumber) {
  Request11002_FieldNumber_Common = 1,
  Request11002_FieldNumber_Params = 2,
};

// 注册
// url: /pilot/register
@interface Request11002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11002_Params *params;

@end

#pragma mark - Request11002_Params

typedef GPB_ENUM(Request11002_Params_FieldNumber) {
  Request11002_Params_FieldNumber_PhoneNumber = 1,
  Request11002_Params_FieldNumber_UserName = 2,
  Request11002_Params_FieldNumber_PwMd5 = 3,
  Request11002_Params_FieldNumber_UserAvatarKey = 4,
};

@interface Request11002_Params : GPBMessage

// 手机号码
@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNumber;

// 用户名
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

// md5加密后的密码
@property(nonatomic, readwrite, copy, null_resettable) NSString *pwMd5;

// userAvatarKey : key 
@property(nonatomic, readwrite, copy, null_resettable) NSString *userAvatarKey;

@end

#pragma mark - Response11002

typedef GPB_ENUM(Response11002_FieldNumber) {
  Response11002_FieldNumber_Common = 1,
  Response11002_FieldNumber_Data_p = 2,
};

@interface Response11002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11002_Data *data_p;

@end

#pragma mark - Response11002_Data

@interface Response11002_Data : GPBMessage

@end

#pragma mark - Request11003

typedef GPB_ENUM(Request11003_FieldNumber) {
  Request11003_FieldNumber_Common = 1,
  Request11003_FieldNumber_Params = 2,
};

// 登录
// url: /pilot/login
@interface Request11003 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11003_Params *params;

@end

#pragma mark - Request11003_Params

typedef GPB_ENUM(Request11003_Params_FieldNumber) {
  Request11003_Params_FieldNumber_Username = 1,
  Request11003_Params_FieldNumber_PwMd5 = 2,
};

@interface Request11003_Params : GPBMessage

// 用户名或手机号
@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

// 加密后的密码
@property(nonatomic, readwrite, copy, null_resettable) NSString *pwMd5;

@end

#pragma mark - Response11003

typedef GPB_ENUM(Response11003_FieldNumber) {
  Response11003_FieldNumber_Common = 1,
  Response11003_FieldNumber_Data_p = 2,
};

@interface Response11003 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11003_Data *data_p;

@end

#pragma mark - Response11003_Data

typedef GPB_ENUM(Response11003_Data_FieldNumber) {
  Response11003_Data_FieldNumber_Key = 1,
  Response11003_Data_FieldNumber_UserName = 2,
  Response11003_Data_FieldNumber_UserAvatar = 3,
  Response11003_Data_FieldNumber_Phone = 4,
  Response11003_Data_FieldNumber_UserId = 5,
};

@interface Response11003_Data : GPBMessage

// 用户私钥
@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userAvatar;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;

@property(nonatomic, readwrite) int32_t userId;

@end

#pragma mark - Request11004

typedef GPB_ENUM(Request11004_FieldNumber) {
  Request11004_FieldNumber_Common = 1,
  Request11004_FieldNumber_Params = 2,
};

// 获取我的收藏
// url: /pilot/getMyCollection
@interface Request11004 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11004_Params *params;

@end

#pragma mark - Request11004_Params

@interface Request11004_Params : GPBMessage

@end

#pragma mark - Response11004

typedef GPB_ENUM(Response11004_FieldNumber) {
  Response11004_FieldNumber_Common = 1,
  Response11004_FieldNumber_Data_p = 2,
};

@interface Response11004 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11004_Data *data_p;

@end

#pragma mark - Response11004_Data

typedef GPB_ENUM(Response11004_Data_FieldNumber) {
  Response11004_Data_FieldNumber_ArticlesArray = 1,
};

@interface Response11004_Data : GPBMessage

// 文章列表
// |articlesArray| contains |Collect|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *articlesArray;
@property(nonatomic, readonly) NSUInteger articlesArray_Count;

@end

#pragma mark - Request11005

typedef GPB_ENUM(Request11005_FieldNumber) {
  Request11005_FieldNumber_Common = 1,
  Request11005_FieldNumber_Params = 2,
};

// 更新个人资料
// url: /pilot/updateUserInfo
@interface Request11005 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11005_Params *params;

@end

#pragma mark - Request11005_Params

typedef GPB_ENUM(Request11005_Params_FieldNumber) {
  Request11005_Params_FieldNumber_UserName = 1,
  Request11005_Params_FieldNumber_AvatarKey = 2,
};

@interface Request11005_Params : GPBMessage

// 用户名
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

// 用户头像key zone__key
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarKey;

@end

#pragma mark - Response11005

typedef GPB_ENUM(Response11005_FieldNumber) {
  Response11005_FieldNumber_Common = 1,
  Response11005_FieldNumber_Data_p = 2,
};

@interface Response11005 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11005_Data *data_p;

@end

#pragma mark - Response11005_Data

@interface Response11005_Data : GPBMessage

@end

#pragma mark - Request11006

typedef GPB_ENUM(Request11006_FieldNumber) {
  Request11006_FieldNumber_Common = 1,
  Request11006_FieldNumber_Params = 2,
};

// 获取 组织 详情
// url: /pilot/getUserDetail
@interface Request11006 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11006_Params *params;

@end

#pragma mark - Request11006_Params

typedef GPB_ENUM(Request11006_Params_FieldNumber) {
  Request11006_Params_FieldNumber_NeedArticles = 1,
  Request11006_Params_FieldNumber_OrgId = 2,
};

@interface Request11006_Params : GPBMessage

// 是否需要返回该用户的文章
@property(nonatomic, readwrite) BOOL needArticles;

// 组织id
@property(nonatomic, readwrite) int32_t orgId;

@end

#pragma mark - Response11006

typedef GPB_ENUM(Response11006_FieldNumber) {
  Response11006_FieldNumber_Common = 1,
  Response11006_FieldNumber_Data_p = 2,
};

@interface Response11006 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11006_Data *data_p;

@end

#pragma mark - Response11006_Data

typedef GPB_ENUM(Response11006_Data_FieldNumber) {
  Response11006_Data_FieldNumber_DetailUser = 1,
};

@interface Response11006_Data : GPBMessage

@property(nonatomic, readwrite) BOOL hasDetailUser;
@property(nonatomic, readwrite, strong, null_resettable) DetailUser *detailUser;

@end

#pragma mark - Request11007

typedef GPB_ENUM(Request11007_FieldNumber) {
  Request11007_FieldNumber_Common = 1,
  Request11007_FieldNumber_Params = 2,
};

// 获取七牛上传token
// url: /pilot/getQiniuToken
@interface Request11007 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11007_Params *params;

@end

#pragma mark - Request11007_Params

@interface Request11007_Params : GPBMessage

@end

#pragma mark - Response11007

typedef GPB_ENUM(Response11007_FieldNumber) {
  Response11007_FieldNumber_Common = 1,
  Response11007_FieldNumber_Data_p = 2,
};

@interface Response11007 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11007_Data *data_p;

@end

#pragma mark - Response11007_Data

typedef GPB_ENUM(Response11007_Data_FieldNumber) {
  Response11007_Data_FieldNumber_Token = 1,
};

@interface Response11007_Data : GPBMessage

// 返回的token
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
