// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reader.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class Article;
@class Request10001_Params;
@class Request10002_Params;
@class Request10003_Params;
@class Request10004_Params;
@class RequestCommon;
@class Response10001_Data;
@class Response10002_Data;
@class Response10003_Data;
@class Response10004_Data;
@class ResponseCommon;
GPB_ENUM_FWD_DECLARE(Category_Enum);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Request10003_OptionType

typedef GPB_ENUM(Request10003_OptionType) {
  Request10003_OptionType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  // 收藏
  Request10003_OptionType_Collect = 0,

  // 取消收藏
  Request10003_OptionType_Uncollect = 1,
};

GPBEnumDescriptor *Request10003_OptionType_EnumDescriptor(void);

BOOL Request10003_OptionType_IsValidValue(int32_t value);

#pragma mark - ReaderRoot

@interface ReaderRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Request10001

typedef GPB_ENUM(Request10001_FieldNumber) {
  Request10001_FieldNumber_Common = 1,
  Request10001_FieldNumber_Params = 2,
};

// 获取文章列表 10001
// url: /articles/getarticles
@interface Request10001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request10001_Params *params;

@end

#pragma mark - Request10001_Params

typedef GPB_ENUM(Request10001_Params_FieldNumber) {
  Request10001_Params_FieldNumber_Category = 1,
  Request10001_Params_FieldNumber_Index = 2,
};

@interface Request10001_Params : GPBMessage

// 请求的文章类型
@property(nonatomic, readwrite) enum Category_Enum category;

// 第几页，第一页是0
@property(nonatomic, readwrite) int32_t index;

@end

int32_t Request10001_Params_Category_RawValue(Request10001_Params *message);
void SetRequest10001_Params_Category_RawValue(Request10001_Params *message, int32_t value);

#pragma mark - Response10001

typedef GPB_ENUM(Response10001_FieldNumber) {
  Response10001_FieldNumber_Common = 1,
  Response10001_FieldNumber_Data_p = 2,
};

@interface Response10001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response10001_Data *data_p;

@end

#pragma mark - Response10001_Data

typedef GPB_ENUM(Response10001_Data_FieldNumber) {
  Response10001_Data_FieldNumber_ArticlesArray = 1,
  Response10001_Data_FieldNumber_MaxCount = 2,
};

@interface Response10001_Data : GPBMessage

// 文章列表
// |articlesArray| contains |Article|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *articlesArray;
@property(nonatomic, readonly) NSUInteger articlesArray_Count;

// 每页的最多个数，如果小于，则没有加载更多
@property(nonatomic, readwrite) int32_t maxCount;

@end

#pragma mark - Request10002

typedef GPB_ENUM(Request10002_FieldNumber) {
  Request10002_FieldNumber_Common = 1,
  Request10002_FieldNumber_Params = 2,
};

// 搜索文章列表 10002
// url: /articles/searchArticles
@interface Request10002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request10002_Params *params;

@end

#pragma mark - Request10002_Params

typedef GPB_ENUM(Request10002_Params_FieldNumber) {
  Request10002_Params_FieldNumber_Keyword = 1,
  Request10002_Params_FieldNumber_Index = 2,
};

@interface Request10002_Params : GPBMessage

// 搜索的关键字
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

// 分页 0,1,2,3...
@property(nonatomic, readwrite) int32_t index;

@end

#pragma mark - Response10002

typedef GPB_ENUM(Response10002_FieldNumber) {
  Response10002_FieldNumber_Common = 1,
  Response10002_FieldNumber_Data_p = 2,
};

@interface Response10002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response10002_Data *data_p;

@end

#pragma mark - Response10002_Data

typedef GPB_ENUM(Response10002_Data_FieldNumber) {
  Response10002_Data_FieldNumber_ArticlesArray = 1,
  Response10002_Data_FieldNumber_MaxCount = 2,
};

@interface Response10002_Data : GPBMessage

// 文章列表
// |articlesArray| contains |Article|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *articlesArray;
@property(nonatomic, readonly) NSUInteger articlesArray_Count;

// 每页的最多个数，如果小于，则没有加载更多
@property(nonatomic, readwrite) int32_t maxCount;

@end

#pragma mark - Request10003

typedef GPB_ENUM(Request10003_FieldNumber) {
  Request10003_FieldNumber_Common = 1,
  Request10003_FieldNumber_Params = 2,
};

// 收藏文章 10003
// url: /articles/collectArticles
@interface Request10003 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request10003_Params *params;

@end

#pragma mark - Request10003_Params

typedef GPB_ENUM(Request10003_Params_FieldNumber) {
  Request10003_Params_FieldNumber_ArticleId = 1,
  Request10003_Params_FieldNumber_Category = 2,
  Request10003_Params_FieldNumber_OptionType = 3,
};

@interface Request10003_Params : GPBMessage

// 文章id
@property(nonatomic, readwrite) int32_t articleId;

// 文章分类
@property(nonatomic, readwrite) enum Category_Enum category;

// 操作类型，取消收藏或者是收藏
@property(nonatomic, readwrite) Request10003_OptionType optionType;

@end

int32_t Request10003_Params_Category_RawValue(Request10003_Params *message);
void SetRequest10003_Params_Category_RawValue(Request10003_Params *message, int32_t value);

int32_t Request10003_Params_OptionType_RawValue(Request10003_Params *message);
void SetRequest10003_Params_OptionType_RawValue(Request10003_Params *message, int32_t value);

#pragma mark - Response10003

typedef GPB_ENUM(Response10003_FieldNumber) {
  Response10003_FieldNumber_Common = 1,
  Response10003_FieldNumber_Data_p = 2,
};

@interface Response10003 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response10003_Data *data_p;

@end

#pragma mark - Response10003_Data

@interface Response10003_Data : GPBMessage

@end

#pragma mark - Request10004

typedef GPB_ENUM(Request10004_FieldNumber) {
  Request10004_FieldNumber_Common = 1,
  Request10004_FieldNumber_Params = 2,
};

// 获取文章（普通图文的文章）详情 10004
// url: /articles/getDetailArticles
@interface Request10004 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request10004_Params *params;

@end

#pragma mark - Request10004_Params

typedef GPB_ENUM(Request10004_Params_FieldNumber) {
  Request10004_Params_FieldNumber_ArticleId = 1,
  Request10004_Params_FieldNumber_Category = 2,
};

@interface Request10004_Params : GPBMessage

// 文章id
@property(nonatomic, readwrite) int32_t articleId;

// 文章分类
@property(nonatomic, readwrite) enum Category_Enum category;

@end

int32_t Request10004_Params_Category_RawValue(Request10004_Params *message);
void SetRequest10004_Params_Category_RawValue(Request10004_Params *message, int32_t value);

#pragma mark - Response10004

typedef GPB_ENUM(Response10004_FieldNumber) {
  Response10004_FieldNumber_Common = 1,
  Response10004_FieldNumber_Data_p = 2,
};

@interface Response10004 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response10004_Data *data_p;

@end

#pragma mark - Response10004_Data

typedef GPB_ENUM(Response10004_Data_FieldNumber) {
  Response10004_Data_FieldNumber_Article = 1,
};

@interface Response10004_Data : GPBMessage

// 文章详情
@property(nonatomic, readwrite) BOOL hasArticle;
@property(nonatomic, readwrite, strong, null_resettable) Article *article;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
