// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.xiang.proto.pilot.nano;

@SuppressWarnings("hiding")
public interface Pilot {

  public static final class Request11001 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string userName = 1;
      public java.lang.String userName;

      public Params() {
        clear();
      }

      public Params clear() {
        userName = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.userName.equals("")) {
          output.writeString(1, this.userName);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.userName.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.userName);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.userName = input.readString();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request11001[] _emptyArray;
    public static Request11001[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request11001[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.pilot.Request11001.Params params = 2;
    public com.xiang.proto.pilot.nano.Pilot.Request11001.Params params;

    public Request11001() {
      clear();
    }

    public Request11001 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request11001 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.pilot.nano.Pilot.Request11001.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request11001 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request11001(), data);
    }

    public static Request11001 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request11001().mergeFrom(input);
    }
  }

  public static final class Response11001 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      public Data() {
        clear();
      }

      public Data clear() {
        cachedSize = -1;
        return this;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response11001[] _emptyArray;
    public static Response11001[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response11001[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.pilot.Response11001.Data data = 2;
    public com.xiang.proto.pilot.nano.Pilot.Response11001.Data data;

    public Response11001() {
      clear();
    }

    public Response11001 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response11001 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.pilot.nano.Pilot.Response11001.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response11001 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response11001(), data);
    }

    public static Response11001 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response11001().mergeFrom(input);
    }
  }

  public static final class Request11002 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string phoneNumber = 1;
      public java.lang.String phoneNumber;

      // optional string userName = 2;
      public java.lang.String userName;

      // optional string pwMd5 = 3;
      public java.lang.String pwMd5;

      // optional string userAvatarKey = 4;
      public java.lang.String userAvatarKey;

      public Params() {
        clear();
      }

      public Params clear() {
        phoneNumber = "";
        userName = "";
        pwMd5 = "";
        userAvatarKey = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.phoneNumber.equals("")) {
          output.writeString(1, this.phoneNumber);
        }
        if (!this.userName.equals("")) {
          output.writeString(2, this.userName);
        }
        if (!this.pwMd5.equals("")) {
          output.writeString(3, this.pwMd5);
        }
        if (!this.userAvatarKey.equals("")) {
          output.writeString(4, this.userAvatarKey);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.phoneNumber.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.phoneNumber);
        }
        if (!this.userName.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(2, this.userName);
        }
        if (!this.pwMd5.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(3, this.pwMd5);
        }
        if (!this.userAvatarKey.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(4, this.userAvatarKey);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.phoneNumber = input.readString();
              break;
            }
            case 18: {
              this.userName = input.readString();
              break;
            }
            case 26: {
              this.pwMd5 = input.readString();
              break;
            }
            case 34: {
              this.userAvatarKey = input.readString();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request11002[] _emptyArray;
    public static Request11002[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request11002[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.pilot.Request11002.Params params = 2;
    public com.xiang.proto.pilot.nano.Pilot.Request11002.Params params;

    public Request11002() {
      clear();
    }

    public Request11002 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request11002 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.pilot.nano.Pilot.Request11002.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request11002 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request11002(), data);
    }

    public static Request11002 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request11002().mergeFrom(input);
    }
  }

  public static final class Response11002 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      public Data() {
        clear();
      }

      public Data clear() {
        cachedSize = -1;
        return this;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response11002[] _emptyArray;
    public static Response11002[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response11002[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.pilot.Response11002.Data data = 2;
    public com.xiang.proto.pilot.nano.Pilot.Response11002.Data data;

    public Response11002() {
      clear();
    }

    public Response11002 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response11002 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.pilot.nano.Pilot.Response11002.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response11002 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response11002(), data);
    }

    public static Response11002 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response11002().mergeFrom(input);
    }
  }

  public static final class Request11003 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string username = 1;
      public java.lang.String username;

      // optional string pwMd5 = 2;
      public java.lang.String pwMd5;

      public Params() {
        clear();
      }

      public Params clear() {
        username = "";
        pwMd5 = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.username.equals("")) {
          output.writeString(1, this.username);
        }
        if (!this.pwMd5.equals("")) {
          output.writeString(2, this.pwMd5);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.username.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.username);
        }
        if (!this.pwMd5.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(2, this.pwMd5);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.username = input.readString();
              break;
            }
            case 18: {
              this.pwMd5 = input.readString();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request11003[] _emptyArray;
    public static Request11003[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request11003[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.pilot.Request11003.Params params = 2;
    public com.xiang.proto.pilot.nano.Pilot.Request11003.Params params;

    public Request11003() {
      clear();
    }

    public Request11003 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request11003 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.pilot.nano.Pilot.Request11003.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request11003 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request11003(), data);
    }

    public static Request11003 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request11003().mergeFrom(input);
    }
  }

  public static final class Response11003 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string key = 1;
      public java.lang.String key;

      // optional string userName = 2;
      public java.lang.String userName;

      // optional string userAvatar = 3;
      public java.lang.String userAvatar;

      // optional string phone = 4;
      public java.lang.String phone;

      // optional int32 userId = 5;
      public int userId;

      public Data() {
        clear();
      }

      public Data clear() {
        key = "";
        userName = "";
        userAvatar = "";
        phone = "";
        userId = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.key.equals("")) {
          output.writeString(1, this.key);
        }
        if (!this.userName.equals("")) {
          output.writeString(2, this.userName);
        }
        if (!this.userAvatar.equals("")) {
          output.writeString(3, this.userAvatar);
        }
        if (!this.phone.equals("")) {
          output.writeString(4, this.phone);
        }
        if (this.userId != 0) {
          output.writeInt32(5, this.userId);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.key.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.key);
        }
        if (!this.userName.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(2, this.userName);
        }
        if (!this.userAvatar.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(3, this.userAvatar);
        }
        if (!this.phone.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(4, this.phone);
        }
        if (this.userId != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(5, this.userId);
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.key = input.readString();
              break;
            }
            case 18: {
              this.userName = input.readString();
              break;
            }
            case 26: {
              this.userAvatar = input.readString();
              break;
            }
            case 34: {
              this.phone = input.readString();
              break;
            }
            case 40: {
              this.userId = input.readInt32();
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response11003[] _emptyArray;
    public static Response11003[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response11003[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.pilot.Response11003.Data data = 2;
    public com.xiang.proto.pilot.nano.Pilot.Response11003.Data data;

    public Response11003() {
      clear();
    }

    public Response11003 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response11003 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.pilot.nano.Pilot.Response11003.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response11003 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response11003(), data);
    }

    public static Response11003 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response11003().mergeFrom(input);
    }
  }

  public static final class Request11004 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      public Params() {
        clear();
      }

      public Params clear() {
        cachedSize = -1;
        return this;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request11004[] _emptyArray;
    public static Request11004[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request11004[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.pilot.Request11004.Params params = 2;
    public com.xiang.proto.pilot.nano.Pilot.Request11004.Params params;

    public Request11004() {
      clear();
    }

    public Request11004 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request11004 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.pilot.nano.Pilot.Request11004.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request11004 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request11004(), data);
    }

    public static Request11004 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request11004().mergeFrom(input);
    }
  }

  public static final class Response11004 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // repeated .com.xiang.proto.Collect articles = 1;
      public com.xiang.proto.nano.Common.Collect[] articles;

      public Data() {
        clear();
      }

      public Data clear() {
        articles = com.xiang.proto.nano.Common.Collect.emptyArray();
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.articles != null && this.articles.length > 0) {
          for (int i = 0; i < this.articles.length; i++) {
            com.xiang.proto.nano.Common.Collect element = this.articles[i];
            if (element != null) {
              output.writeMessage(1, element);
            }
          }
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.articles != null && this.articles.length > 0) {
          for (int i = 0; i < this.articles.length; i++) {
            com.xiang.proto.nano.Common.Collect element = this.articles[i];
            if (element != null) {
              size += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(1, element);
            }
          }
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              int arrayLength = com.google.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 10);
              int i = this.articles == null ? 0 : this.articles.length;
              com.xiang.proto.nano.Common.Collect[] newArray =
                  new com.xiang.proto.nano.Common.Collect[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.articles, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new com.xiang.proto.nano.Common.Collect();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new com.xiang.proto.nano.Common.Collect();
              input.readMessage(newArray[i]);
              this.articles = newArray;
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response11004[] _emptyArray;
    public static Response11004[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response11004[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.pilot.Response11004.Data data = 2;
    public com.xiang.proto.pilot.nano.Pilot.Response11004.Data data;

    public Response11004() {
      clear();
    }

    public Response11004 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response11004 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.pilot.nano.Pilot.Response11004.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response11004 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response11004(), data);
    }

    public static Response11004 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response11004().mergeFrom(input);
    }
  }

  public static final class Request11005 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string userName = 1;
      public java.lang.String userName;

      // optional string avatarKey = 2;
      public java.lang.String avatarKey;

      public Params() {
        clear();
      }

      public Params clear() {
        userName = "";
        avatarKey = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.userName.equals("")) {
          output.writeString(1, this.userName);
        }
        if (!this.avatarKey.equals("")) {
          output.writeString(2, this.avatarKey);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.userName.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.userName);
        }
        if (!this.avatarKey.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(2, this.avatarKey);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.userName = input.readString();
              break;
            }
            case 18: {
              this.avatarKey = input.readString();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request11005[] _emptyArray;
    public static Request11005[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request11005[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.pilot.Request11005.Params params = 2;
    public com.xiang.proto.pilot.nano.Pilot.Request11005.Params params;

    public Request11005() {
      clear();
    }

    public Request11005 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request11005 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.pilot.nano.Pilot.Request11005.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request11005 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request11005(), data);
    }

    public static Request11005 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request11005().mergeFrom(input);
    }
  }

  public static final class Response11005 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      public Data() {
        clear();
      }

      public Data clear() {
        cachedSize = -1;
        return this;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response11005[] _emptyArray;
    public static Response11005[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response11005[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.pilot.Response11005.Data data = 2;
    public com.xiang.proto.pilot.nano.Pilot.Response11005.Data data;

    public Response11005() {
      clear();
    }

    public Response11005 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response11005 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.pilot.nano.Pilot.Response11005.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response11005 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response11005(), data);
    }

    public static Response11005 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response11005().mergeFrom(input);
    }
  }

  public static final class Request11006 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional bool needArticles = 1;
      public boolean needArticles;

      // optional int32 orgId = 2;
      public int orgId;

      public Params() {
        clear();
      }

      public Params clear() {
        needArticles = false;
        orgId = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.needArticles != false) {
          output.writeBool(1, this.needArticles);
        }
        if (this.orgId != 0) {
          output.writeInt32(2, this.orgId);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.needArticles != false) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeBoolSize(1, this.needArticles);
        }
        if (this.orgId != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(2, this.orgId);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              this.needArticles = input.readBool();
              break;
            }
            case 16: {
              this.orgId = input.readInt32();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request11006[] _emptyArray;
    public static Request11006[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request11006[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.pilot.Request11006.Params params = 2;
    public com.xiang.proto.pilot.nano.Pilot.Request11006.Params params;

    public Request11006() {
      clear();
    }

    public Request11006 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request11006 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.pilot.nano.Pilot.Request11006.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request11006 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request11006(), data);
    }

    public static Request11006 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request11006().mergeFrom(input);
    }
  }

  public static final class Response11006 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .com.xiang.proto.DetailUser detailUser = 1;
      public com.xiang.proto.nano.Common.DetailUser detailUser;

      public Data() {
        clear();
      }

      public Data clear() {
        detailUser = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.detailUser != null) {
          output.writeMessage(1, this.detailUser);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.detailUser != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.detailUser);
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.detailUser == null) {
                this.detailUser = new com.xiang.proto.nano.Common.DetailUser();
              }
              input.readMessage(this.detailUser);
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response11006[] _emptyArray;
    public static Response11006[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response11006[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.pilot.Response11006.Data data = 2;
    public com.xiang.proto.pilot.nano.Pilot.Response11006.Data data;

    public Response11006() {
      clear();
    }

    public Response11006 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response11006 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.pilot.nano.Pilot.Response11006.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response11006 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response11006(), data);
    }

    public static Response11006 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response11006().mergeFrom(input);
    }
  }

  public static final class Request11007 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      public Params() {
        clear();
      }

      public Params clear() {
        cachedSize = -1;
        return this;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request11007[] _emptyArray;
    public static Request11007[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request11007[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.pilot.Request11007.Params params = 2;
    public com.xiang.proto.pilot.nano.Pilot.Request11007.Params params;

    public Request11007() {
      clear();
    }

    public Request11007 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request11007 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.pilot.nano.Pilot.Request11007.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request11007 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request11007(), data);
    }

    public static Request11007 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request11007().mergeFrom(input);
    }
  }

  public static final class Response11007 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string token = 1;
      public java.lang.String token;

      public Data() {
        clear();
      }

      public Data clear() {
        token = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.token.equals("")) {
          output.writeString(1, this.token);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.token.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.token);
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.token = input.readString();
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response11007[] _emptyArray;
    public static Response11007[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response11007[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.pilot.Response11007.Data data = 2;
    public com.xiang.proto.pilot.nano.Pilot.Response11007.Data data;

    public Response11007() {
      clear();
    }

    public Response11007 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response11007 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.pilot.nano.Pilot.Response11007.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response11007 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response11007(), data);
    }

    public static Response11007 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response11007().mergeFrom(input);
    }
  }
}
